name: Unit Tests V2
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  unit-tests:
    name: 🧪 Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '16'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --frozen-lockfile --ignore-scripts
      - name: Build test (TypeScript compile)
        run: yarn build-test || true
      - name: Yarn test
        shell: bash
        env:
          TS_NODE_TRANSPILE_ONLY: 'true'
          V2_TEST: '1'
        run: node_modules/.bin/mocha 'src/**/__tests__/*.test.ts'
